project1tokenizer: simpleUI.o tokenizer.o history.o
		cc -o project1tokenizer simpleUI.o tokenizer.o history.o

simpleUI.o: simpleUI.c tokenizer.h history.h

history.o: history.c history.h

tokenizer.o: tokenizer.c tokenizer.h

clean: rm project1tokenizer *.o
